package main

const (
	vocabLanguage         = "ja"
	vocabProficiencyLevel = "N5"
	vocabDifficulty       = 2
)

type vocabWord struct {
	ID           string
	Kana         string
	Kanji        string
	MeaningKo    string
	PartOfSpeech string
}

var n5Words = []vocabWord{
	{ID: "n5_word_001", Kana: "わたし", Kanji: "私", MeaningKo: "나", PartOfSpeech: "pronoun"},
	{ID: "n5_word_002", Kana: "あなた", Kanji: "あなた", MeaningKo: "당신", PartOfSpeech: "pronoun"},
	{ID: "n5_word_003", Kana: "ひと", Kanji: "人", MeaningKo: "사람", PartOfSpeech: "noun"},
	{ID: "n5_word_004", Kana: "おとこ", Kanji: "男", MeaningKo: "남자", PartOfSpeech: "noun"},
	{ID: "n5_word_005", Kana: "おんな", Kanji: "女", MeaningKo: "여자", PartOfSpeech: "noun"},
	{ID: "n5_word_006", Kana: "こども", Kanji: "子供", MeaningKo: "아이", PartOfSpeech: "noun"},
	{ID: "n5_word_007", Kana: "ともだち", Kanji: "友達", MeaningKo: "친구", PartOfSpeech: "noun"},
	{ID: "n5_word_008", Kana: "せんせい", Kanji: "先生", MeaningKo: "선생님", PartOfSpeech: "noun"},
	{ID: "n5_word_009", Kana: "がくせい", Kanji: "学生", MeaningKo: "학생", PartOfSpeech: "noun"},
	{ID: "n5_word_010", Kana: "がっこう", Kanji: "学校", MeaningKo: "학교", PartOfSpeech: "noun"},
	{ID: "n5_word_011", Kana: "だいがく", Kanji: "大学", MeaningKo: "대학교", PartOfSpeech: "noun"},
	{ID: "n5_word_012", Kana: "いえ", Kanji: "家", MeaningKo: "집", PartOfSpeech: "noun"},
	{ID: "n5_word_013", Kana: "へや", Kanji: "部屋", MeaningKo: "방", PartOfSpeech: "noun"},
	{ID: "n5_word_014", Kana: "えき", Kanji: "駅", MeaningKo: "역", PartOfSpeech: "noun"},
	{ID: "n5_word_015", Kana: "みせ", Kanji: "店", MeaningKo: "가게", PartOfSpeech: "noun"},
	{ID: "n5_word_016", Kana: "かいしゃ", Kanji: "会社", MeaningKo: "회사", PartOfSpeech: "noun"},
	{ID: "n5_word_017", Kana: "びょういん", Kanji: "病院", MeaningKo: "병원", PartOfSpeech: "noun"},
	{ID: "n5_word_018", Kana: "ほん", Kanji: "本", MeaningKo: "책", PartOfSpeech: "noun"},
	{ID: "n5_word_019", Kana: "じしょ", Kanji: "辞書", MeaningKo: "사전", PartOfSpeech: "noun"},
	{ID: "n5_word_020", Kana: "てがみ", Kanji: "手紙", MeaningKo: "편지", PartOfSpeech: "noun"},
	{ID: "n5_word_021", Kana: "くるま", Kanji: "車", MeaningKo: "자동차", PartOfSpeech: "noun"},
	{ID: "n5_word_022", Kana: "でんしゃ", Kanji: "電車", MeaningKo: "전철", PartOfSpeech: "noun"},
	{ID: "n5_word_023", Kana: "じてんしゃ", Kanji: "自転車", MeaningKo: "자전거", PartOfSpeech: "noun"},
	{ID: "n5_word_024", Kana: "みず", Kanji: "水", MeaningKo: "물", PartOfSpeech: "noun"},
	{ID: "n5_word_025", Kana: "おちゃ", Kanji: "お茶", MeaningKo: "차", PartOfSpeech: "noun"},
	{ID: "n5_word_026", Kana: "ごはん", Kanji: "ご飯", MeaningKo: "밥", PartOfSpeech: "noun"},
	{ID: "n5_word_027", Kana: "さかな", Kanji: "魚", MeaningKo: "생선", PartOfSpeech: "noun"},
	{ID: "n5_word_028", Kana: "にく", Kanji: "肉", MeaningKo: "고기", PartOfSpeech: "noun"},
	{ID: "n5_word_029", Kana: "たまご", Kanji: "卵", MeaningKo: "달걀", PartOfSpeech: "noun"},
	{ID: "n5_word_030", Kana: "くだもの", Kanji: "果物", MeaningKo: "과일", PartOfSpeech: "noun"},
	{ID: "n5_word_031", Kana: "ねこ", Kanji: "猫", MeaningKo: "고양이", PartOfSpeech: "noun"},
	{ID: "n5_word_032", Kana: "いぬ", Kanji: "犬", MeaningKo: "개", PartOfSpeech: "noun"},
	{ID: "n5_word_033", Kana: "やま", Kanji: "山", MeaningKo: "산", PartOfSpeech: "noun"},
	{ID: "n5_word_034", Kana: "かわ", Kanji: "川", MeaningKo: "강", PartOfSpeech: "noun"},
	{ID: "n5_word_035", Kana: "あめ", Kanji: "雨", MeaningKo: "비", PartOfSpeech: "noun"},
	{ID: "n5_word_036", Kana: "ゆき", Kanji: "雪", MeaningKo: "눈", PartOfSpeech: "noun"},
	{ID: "n5_word_037", Kana: "ひ", Kanji: "日", MeaningKo: "해", PartOfSpeech: "noun"},
	{ID: "n5_word_038", Kana: "つき", Kanji: "月", MeaningKo: "달", PartOfSpeech: "noun"},
	{ID: "n5_word_039", Kana: "ひ", Kanji: "火", MeaningKo: "불", PartOfSpeech: "noun"},
	{ID: "n5_word_040", Kana: "き", Kanji: "木", MeaningKo: "나무", PartOfSpeech: "noun"},
	{ID: "n5_word_041", Kana: "きん", Kanji: "金", MeaningKo: "금", PartOfSpeech: "noun"},
	{ID: "n5_word_042", Kana: "つち", Kanji: "土", MeaningKo: "흙", PartOfSpeech: "noun"},
	{ID: "n5_word_043", Kana: "きょう", Kanji: "今日", MeaningKo: "오늘", PartOfSpeech: "noun"},
	{ID: "n5_word_044", Kana: "あした", Kanji: "明日", MeaningKo: "내일", PartOfSpeech: "noun"},
	{ID: "n5_word_045", Kana: "きのう", Kanji: "昨日", MeaningKo: "어제", PartOfSpeech: "noun"},
	{ID: "n5_word_046", Kana: "あさ", Kanji: "朝", MeaningKo: "아침", PartOfSpeech: "noun"},
	{ID: "n5_word_047", Kana: "ひる", Kanji: "昼", MeaningKo: "낮", PartOfSpeech: "noun"},
	{ID: "n5_word_048", Kana: "よる", Kanji: "夜", MeaningKo: "밤", PartOfSpeech: "noun"},
	{ID: "n5_word_049", Kana: "いま", Kanji: "今", MeaningKo: "지금", PartOfSpeech: "noun"},
	{ID: "n5_word_050", Kana: "まいにち", Kanji: "毎日", MeaningKo: "매일", PartOfSpeech: "noun"},
	{ID: "n5_word_051", Kana: "うえ", Kanji: "上", MeaningKo: "위", PartOfSpeech: "noun"},
	{ID: "n5_word_052", Kana: "した", Kanji: "下", MeaningKo: "아래", PartOfSpeech: "noun"},
	{ID: "n5_word_053", Kana: "なか", Kanji: "中", MeaningKo: "안", PartOfSpeech: "noun"},
	{ID: "n5_word_054", Kana: "まえ", Kanji: "前", MeaningKo: "앞", PartOfSpeech: "noun"},
	{ID: "n5_word_055", Kana: "うしろ", Kanji: "後ろ", MeaningKo: "뒤", PartOfSpeech: "noun"},
	{ID: "n5_word_056", Kana: "みぎ", Kanji: "右", MeaningKo: "오른쪽", PartOfSpeech: "noun"},
	{ID: "n5_word_057", Kana: "ひだり", Kanji: "左", MeaningKo: "왼쪽", PartOfSpeech: "noun"},
	{ID: "n5_word_058", Kana: "いち", Kanji: "一", MeaningKo: "하나", PartOfSpeech: "numeral"},
	{ID: "n5_word_059", Kana: "に", Kanji: "二", MeaningKo: "둘", PartOfSpeech: "numeral"},
	{ID: "n5_word_060", Kana: "さん", Kanji: "三", MeaningKo: "셋", PartOfSpeech: "numeral"},
	{ID: "n5_word_061", Kana: "よん", Kanji: "四", MeaningKo: "넷", PartOfSpeech: "numeral"},
	{ID: "n5_word_062", Kana: "ご", Kanji: "五", MeaningKo: "다섯", PartOfSpeech: "numeral"},
	{ID: "n5_word_063", Kana: "ろく", Kanji: "六", MeaningKo: "여섯", PartOfSpeech: "numeral"},
	{ID: "n5_word_064", Kana: "なな", Kanji: "七", MeaningKo: "일곱", PartOfSpeech: "numeral"},
	{ID: "n5_word_065", Kana: "はち", Kanji: "八", MeaningKo: "여덟", PartOfSpeech: "numeral"},
	{ID: "n5_word_066", Kana: "きゅう", Kanji: "九", MeaningKo: "아홉", PartOfSpeech: "numeral"},
	{ID: "n5_word_067", Kana: "じゅう", Kanji: "十", MeaningKo: "열", PartOfSpeech: "numeral"},
	{ID: "n5_word_068", Kana: "ひゃく", Kanji: "百", MeaningKo: "백", PartOfSpeech: "numeral"},
	{ID: "n5_word_069", Kana: "せん", Kanji: "千", MeaningKo: "천", PartOfSpeech: "numeral"},
	{ID: "n5_word_070", Kana: "まん", Kanji: "万", MeaningKo: "만", PartOfSpeech: "numeral"},
	{ID: "n5_word_071", Kana: "えん", Kanji: "円", MeaningKo: "엔", PartOfSpeech: "noun"},
	{ID: "n5_word_072", Kana: "いく", Kanji: "行く", MeaningKo: "가다", PartOfSpeech: "verb"},
	{ID: "n5_word_073", Kana: "くる", Kanji: "来る", MeaningKo: "오다", PartOfSpeech: "verb"},
	{ID: "n5_word_074", Kana: "みる", Kanji: "見る", MeaningKo: "보다", PartOfSpeech: "verb"},
	{ID: "n5_word_075", Kana: "たべる", Kanji: "食べる", MeaningKo: "먹다", PartOfSpeech: "verb"},
	{ID: "n5_word_076", Kana: "のむ", Kanji: "飲む", MeaningKo: "마시다", PartOfSpeech: "verb"},
	{ID: "n5_word_077", Kana: "よむ", Kanji: "読む", MeaningKo: "읽다", PartOfSpeech: "verb"},
	{ID: "n5_word_078", Kana: "かく", Kanji: "書く", MeaningKo: "쓰다", PartOfSpeech: "verb"},
	{ID: "n5_word_079", Kana: "きく", Kanji: "聞く", MeaningKo: "듣다", PartOfSpeech: "verb"},
	{ID: "n5_word_080", Kana: "はなす", Kanji: "話す", MeaningKo: "말하다", PartOfSpeech: "verb"},
	{ID: "n5_word_081", Kana: "かう", Kanji: "買う", MeaningKo: "사다", PartOfSpeech: "verb"},
	{ID: "n5_word_082", Kana: "ある", Kanji: "ある", MeaningKo: "있다", PartOfSpeech: "verb"},
	{ID: "n5_word_083", Kana: "いる", Kanji: "いる", MeaningKo: "있다", PartOfSpeech: "verb"},
	{ID: "n5_word_084", Kana: "する", Kanji: "する", MeaningKo: "하다", PartOfSpeech: "verb"},
	{ID: "n5_word_085", Kana: "おおきい", Kanji: "大きい", MeaningKo: "크다", PartOfSpeech: "adjective"},
	{ID: "n5_word_086", Kana: "ちいさい", Kanji: "小さい", MeaningKo: "작다", PartOfSpeech: "adjective"},
	{ID: "n5_word_087", Kana: "たかい", Kanji: "高い", MeaningKo: "비싸다/높다", PartOfSpeech: "adjective"},
	{ID: "n5_word_088", Kana: "やすい", Kanji: "安い", MeaningKo: "싸다", PartOfSpeech: "adjective"},
	{ID: "n5_word_089", Kana: "あたらしい", Kanji: "新しい", MeaningKo: "새롭다", PartOfSpeech: "adjective"},
	{ID: "n5_word_090", Kana: "ふるい", Kanji: "古い", MeaningKo: "오래되다", PartOfSpeech: "adjective"},
	{ID: "n5_word_091", Kana: "あつい", Kanji: "暑い", MeaningKo: "덥다", PartOfSpeech: "adjective"},
	{ID: "n5_word_092", Kana: "さむい", Kanji: "寒い", MeaningKo: "춥다", PartOfSpeech: "adjective"},
	{ID: "n5_word_093", Kana: "いい", Kanji: "良い", MeaningKo: "좋다", PartOfSpeech: "adjective"},
	{ID: "n5_word_094", Kana: "わるい", Kanji: "悪い", MeaningKo: "나쁘다", PartOfSpeech: "adjective"},
	{ID: "n5_word_095", Kana: "テレビ", Kanji: "テレビ", MeaningKo: "TV", PartOfSpeech: "noun"},
	{ID: "n5_word_096", Kana: "コーヒー", Kanji: "コーヒー", MeaningKo: "커피", PartOfSpeech: "noun"},
	{ID: "n5_word_097", Kana: "パン", Kanji: "パン", MeaningKo: "빵", PartOfSpeech: "noun"},
	{ID: "n5_word_098", Kana: "タクシー", Kanji: "タクシー", MeaningKo: "택시", PartOfSpeech: "noun"},
	{ID: "n5_word_099", Kana: "ホテル", Kanji: "ホテル", MeaningKo: "호텔", PartOfSpeech: "noun"},
	{ID: "n5_word_100", Kana: "トイレ", Kanji: "トイレ", MeaningKo: "화장실", PartOfSpeech: "noun"},
	{ID: "n5_word_101", Kana: "おとうさん", Kanji: "お父さん", MeaningKo: "아버지", PartOfSpeech: "noun"},
	{ID: "n5_word_102", Kana: "おかあさん", Kanji: "お母さん", MeaningKo: "어머니", PartOfSpeech: "noun"},
	{ID: "n5_word_103", Kana: "おにいさん", Kanji: "お兄さん", MeaningKo: "형/오빠", PartOfSpeech: "noun"},
	{ID: "n5_word_104", Kana: "おねえさん", Kanji: "お姉さん", MeaningKo: "누나/언니", PartOfSpeech: "noun"},
	{ID: "n5_word_105", Kana: "おとうと", Kanji: "弟", MeaningKo: "남동생", PartOfSpeech: "noun"},
	{ID: "n5_word_106", Kana: "いもうと", Kanji: "妹", MeaningKo: "여동생", PartOfSpeech: "noun"},
	{ID: "n5_word_107", Kana: "きょうだい", Kanji: "兄弟", MeaningKo: "형제", PartOfSpeech: "noun"},
	{ID: "n5_word_108", Kana: "そふ", Kanji: "祖父", MeaningKo: "할아버지", PartOfSpeech: "noun"},
	{ID: "n5_word_109", Kana: "そぼ", Kanji: "祖母", MeaningKo: "할머니", PartOfSpeech: "noun"},
	{ID: "n5_word_110", Kana: "おじいさん", Kanji: "お爺さん", MeaningKo: "할아버지 (존칭)", PartOfSpeech: "noun"},
	{ID: "n5_word_111", Kana: "おばあさん", Kanji: "お婆さん", MeaningKo: "할머니 (존칭)", PartOfSpeech: "noun"},
	{ID: "n5_word_112", Kana: "こくばん", Kanji: "黒板", MeaningKo: "칠판", PartOfSpeech: "noun"},
	{ID: "n5_word_113", Kana: "いす", Kanji: "椅子", MeaningKo: "의자", PartOfSpeech: "noun"},
	{ID: "n5_word_114", Kana: "つくえ", Kanji: "机", MeaningKo: "책상", PartOfSpeech: "noun"},
	{ID: "n5_word_115", Kana: "えいご", Kanji: "英語", MeaningKo: "영어", PartOfSpeech: "noun"},
	{ID: "n5_word_116", Kana: "にほんご", Kanji: "日本語", MeaningKo: "일본어", PartOfSpeech: "noun"},
	{ID: "n5_word_117", Kana: "ちゅうごくご", Kanji: "中国語", MeaningKo: "중국어", PartOfSpeech: "noun"},
	{ID: "n5_word_118", Kana: "かんこくご", Kanji: "韓国語", MeaningKo: "한국어", PartOfSpeech: "noun"},
	{ID: "n5_word_119", Kana: "がくぶ", Kanji: "学部", MeaningKo: "학부", PartOfSpeech: "noun"},
	{ID: "n5_word_120", Kana: "せんもん", Kanji: "専門", MeaningKo: "전공", PartOfSpeech: "noun"},
	{ID: "n5_word_121", Kana: "せんこう", Kanji: "専攻", MeaningKo: "전공", PartOfSpeech: "noun"},
	{ID: "n5_word_122", Kana: "りゅうがくせい", Kanji: "留学生", MeaningKo: "유학생", PartOfSpeech: "noun"},
	{ID: "n5_word_123", Kana: "だれ", Kanji: "誰", MeaningKo: "누구", PartOfSpeech: "pronoun"},
	{ID: "n5_word_124", Kana: "なに", Kanji: "何", MeaningKo: "무엇", PartOfSpeech: "pronoun"},
	{ID: "n5_word_125", Kana: "いつ", Kanji: "いつ", MeaningKo: "언제", PartOfSpeech: "adverb"},
	{ID: "n5_word_126", Kana: "どこ", Kanji: "どこ", MeaningKo: "어디", PartOfSpeech: "adverb"},
	{ID: "n5_word_127", Kana: "どう", Kanji: "どう", MeaningKo: "어떻게", PartOfSpeech: "adverb"},
	{ID: "n5_word_128", Kana: "なぜ", Kanji: "なぜ", MeaningKo: "왜", PartOfSpeech: "adverb"},
	{ID: "n5_word_129", Kana: "これ", Kanji: "これ", MeaningKo: "이것", PartOfSpeech: "pronoun"},
	{ID: "n5_word_130", Kana: "それ", Kanji: "それ", MeaningKo: "그것", PartOfSpeech: "pronoun"},
	{ID: "n5_word_131", Kana: "あれ", Kanji: "あれ", MeaningKo: "저것", PartOfSpeech: "pronoun"},
	{ID: "n5_word_132", Kana: "この", Kanji: "この", MeaningKo: "이(것)", PartOfSpeech: "adjective"},
	{ID: "n5_word_133", Kana: "その", Kanji: "その", MeaningKo: "그(것)", PartOfSpeech: "adjective"},
	{ID: "n5_word_134", Kana: "あの", Kanji: "あの", MeaningKo: "저(것)", PartOfSpeech: "adjective"},
	{ID: "n5_word_135", Kana: "ここ", Kanji: "ここ", MeaningKo: "여기", PartOfSpeech: "adverb"},
	{ID: "n5_word_136", Kana: "そこ", Kanji: "そこ", MeaningKo: "거기", PartOfSpeech: "adverb"},
	{ID: "n5_word_137", Kana: "あそこ", Kanji: "あそこ", MeaningKo: "저기", PartOfSpeech: "adverb"},
	{ID: "n5_word_138", Kana: "げつようび", Kanji: "月曜日", MeaningKo: "월요일", PartOfSpeech: "noun"},
	{ID: "n5_word_139", Kana: "かようび", Kanji: "火曜日", MeaningKo: "화요일", PartOfSpeech: "noun"},
	{ID: "n5_word_140", Kana: "すいようび", Kanji: "水曜日", MeaningKo: "수요일", PartOfSpeech: "noun"},
	{ID: "n5_word_141", Kana: "もくようび", Kanji: "木曜日", MeaningKo: "목요일", PartOfSpeech: "noun"},
	{ID: "n5_word_142", Kana: "きんようび", Kanji: "金曜日", MeaningKo: "금요일", PartOfSpeech: "noun"},
	{ID: "n5_word_143", Kana: "どようび", Kanji: "土曜日", MeaningKo: "토요일", PartOfSpeech: "noun"},
	{ID: "n5_word_144", Kana: "にちようび", Kanji: "日曜日", MeaningKo: "일요일", PartOfSpeech: "noun"},
	{ID: "n5_word_145", Kana: "しゅう", Kanji: "週", MeaningKo: "주", PartOfSpeech: "noun"},
	{ID: "n5_word_146", Kana: "せんしゅう", Kanji: "先週", MeaningKo: "지난주", PartOfSpeech: "noun"},
	{ID: "n5_word_147", Kana: "こんしゅう", Kanji: "今週", MeaningKo: "이번 주", PartOfSpeech: "noun"},
	{ID: "n5_word_148", Kana: "らいしゅう", Kanji: "来週", MeaningKo: "다음 주", PartOfSpeech: "noun"},
	{ID: "n5_word_149", Kana: "つき", Kanji: "月", MeaningKo: "월", PartOfSpeech: "noun"},
	{ID: "n5_word_150", Kana: "せんげつ", Kanji: "先月", MeaningKo: "지난달", PartOfSpeech: "noun"},
	{ID: "n5_word_151", Kana: "こんげつ", Kanji: "今月", MeaningKo: "이번 달", PartOfSpeech: "noun"},
	{ID: "n5_word_152", Kana: "らいげつ", Kanji: "来月", MeaningKo: "다음 달", PartOfSpeech: "noun"},
	{ID: "n5_word_153", Kana: "ことし", Kanji: "今年", MeaningKo: "올해", PartOfSpeech: "noun"},
	{ID: "n5_word_154", Kana: "きょねん", Kanji: "去年", MeaningKo: "작년", PartOfSpeech: "noun"},
	{ID: "n5_word_155", Kana: "らいねん", Kanji: "来年", MeaningKo: "내년", PartOfSpeech: "noun"},
	{ID: "n5_word_156", Kana: "じかん", Kanji: "時間", MeaningKo: "시간", PartOfSpeech: "noun"},
	{ID: "n5_word_157", Kana: "ふん", Kanji: "分", MeaningKo: "분", PartOfSpeech: "noun"},
	{ID: "n5_word_158", Kana: "はん", Kanji: "半", MeaningKo: "반", PartOfSpeech: "noun"},
	{ID: "n5_word_159", Kana: "なんじ", Kanji: "何時", MeaningKo: "몇 시", PartOfSpeech: "noun"},
	{ID: "n5_word_160", Kana: "えいが", Kanji: "映画", MeaningKo: "영화", PartOfSpeech: "noun"},
	{ID: "n5_word_161", Kana: "ごぜん", Kanji: "午前", MeaningKo: "오전", PartOfSpeech: "noun"},
	{ID: "n5_word_162", Kana: "ごご", Kanji: "午後", MeaningKo: "오후", PartOfSpeech: "noun"},
	{ID: "n5_word_163", Kana: "まいあさ", Kanji: "毎朝", MeaningKo: "매일 아침", PartOfSpeech: "noun"},
	{ID: "n5_word_164", Kana: "まいばん", Kanji: "毎晩", MeaningKo: "매일 밤", PartOfSpeech: "noun"},
	{ID: "n5_word_165", Kana: "どうぞ", Kanji: "どうぞ", MeaningKo: "부디/아무쪼록", PartOfSpeech: "adverb"},
	{ID: "n5_word_166", Kana: "どうも", Kanji: "どうも", MeaningKo: "고맙습니다/어쩐지", PartOfSpeech: "adverb"},
	{ID: "n5_word_167", Kana: "ありがとう", Kanji: "ありがとう", MeaningKo: "고마워", PartOfSpeech: "expression"},
	{ID: "n5_word_168", Kana: "すみません", Kanji: "すみません", MeaningKo: "미안합니다/실례합니다", PartOfSpeech: "expression"},
	{ID: "n5_word_169", Kana: "ごめんなさい", Kanji: "ごめんなさい", MeaningKo: "미안해", PartOfSpeech: "expression"},
	{ID: "n5_word_170", Kana: "おはよう", Kanji: "おはよう", MeaningKo: "안녕 (아침)", PartOfSpeech: "expression"},
	{ID: "n5_word_171", Kana: "こんにちは", Kanji: "こんにちは", MeaningKo: "안녕하세요 (낮)", PartOfSpeech: "expression"},
	{ID: "n5_word_172", Kana: "こんばんは", Kanji: "こんばんは", MeaningKo: "안녕하세요 (저녁)", PartOfSpeech: "expression"},
	{ID: "n5_word_173", Kana: "さようなら", Kanji: "さようなら", MeaningKo: "안녕히 계세요", PartOfSpeech: "expression"},
	{ID: "n5_word_174", Kana: "おやすみ", Kanji: "お休み", MeaningKo: "안녕히 주무세요", PartOfSpeech: "expression"},
	{ID: "n5_word_175", Kana: "はじめまして", Kanji: "はじめまして", MeaningKo: "처음 뵙겠습니다", PartOfSpeech: "expression"},
	{ID: "n5_word_176", Kana: "よろしくおねがいします", Kanji: "よろしくお願いします", MeaningKo: "잘 부탁드립니다", PartOfSpeech: "expression"},
	{ID: "n5_word_177", Kana: "いただきます", Kanji: "いただきます", MeaningKo: "잘 먹겠습니다", PartOfSpeech: "expression"},
	{ID: "n5_word_178", Kana: "ごちそうさま", Kanji: "ご馳走様", MeaningKo: "잘 먹었습니다", PartOfSpeech: "expression"},
	{ID: "n5_word_179", Kana: "いってきます", Kanji: "行ってきます", MeaningKo: "다녀오겠습니다", PartOfSpeech: "expression"},
	{ID: "n5_word_180", Kana: "いってらっしゃい", Kanji: "いってらっしゃい", MeaningKo: "다녀오세요", PartOfSpeech: "expression"},
	{ID: "n5_word_181", Kana: "ただいま", Kanji: "ただいま", MeaningKo: "다녀왔습니다", PartOfSpeech: "expression"},
	{ID: "n5_word_182", Kana: "おかえりなさい", Kanji: "お帰りなさい", MeaningKo: "다녀오셨어요", PartOfSpeech: "expression"},
	{ID: "n5_word_183", Kana: "おめでとう", Kanji: "おめでとう", MeaningKo: "축하합니다", PartOfSpeech: "expression"},
	{ID: "n5_word_184", Kana: "がんばって", Kanji: "頑張って", MeaningKo: "힘내세요", PartOfSpeech: "expression"},
	{ID: "n5_word_185", Kana: "もしもし", Kanji: "もしもし", MeaningKo: "여보세요", PartOfSpeech: "expression"},
	{ID: "n5_word_186", Kana: "はい", Kanji: "はい", MeaningKo: "네/예", PartOfSpeech: "expression"},
	{ID: "n5_word_187", Kana: "いいえ", Kanji: "いいえ", MeaningKo: "아니요", PartOfSpeech: "expression"},
	{ID: "n5_word_188", Kana: "わかる", Kanji: "分かる", MeaningKo: "알다", PartOfSpeech: "verb"},
	{ID: "n5_word_189", Kana: "しる", Kanji: "知る", MeaningKo: "알다", PartOfSpeech: "verb"},
	{ID: "n5_word_190", Kana: "おもう", Kanji: "思う", MeaningKo: "생각하다", PartOfSpeech: "verb"},
	{ID: "n5_word_191", Kana: "いう", Kanji: "言う", MeaningKo: "말하다", PartOfSpeech: "verb"},
	{ID: "n5_word_192", Kana: "でる", Kanji: "出る", MeaningKo: "나가다", PartOfSpeech: "verb"},
	{ID: "n5_word_193", Kana: "はいる", Kanji: "入る", MeaningKo: "들어가다", PartOfSpeech: "verb"},
	{ID: "n5_word_194", Kana: "きる", Kanji: "切る", MeaningKo: "자르다", PartOfSpeech: "verb"},
	{ID: "n5_word_195", Kana: "つく", Kanji: "着く", MeaningKo: "도착하다", PartOfSpeech: "verb"},
	{ID: "n5_word_196", Kana: "もつ", Kanji: "持つ", MeaningKo: "가지다", PartOfSpeech: "verb"},
	{ID: "n5_word_197", Kana: "まつ", Kanji: "待つ", MeaningKo: "기다리다", PartOfSpeech: "verb"},
	{ID: "n5_word_198", Kana: "とる", Kanji: "取る", MeaningKo: "집다/가지다", PartOfSpeech: "verb"},
	{ID: "n5_word_199", Kana: "とる", Kanji: "撮る", MeaningKo: "찍다 (사진)", PartOfSpeech: "verb"},
	{ID: "n5_word_200", Kana: "あける", Kanji: "開ける", MeaningKo: "열다", PartOfSpeech: "verb"},
	{ID: "n5_word_201", Kana: "ぎんこう", Kanji: "銀行", MeaningKo: "은행", PartOfSpeech: "noun"},
	{ID: "n5_word_202", Kana: "ゆうびんきょく", Kanji: "郵便局", MeaningKo: "우체국", PartOfSpeech: "noun"},
	{ID: "n5_word_203", Kana: "こうえん", Kanji: "公園", MeaningKo: "공원", PartOfSpeech: "noun"},
	{ID: "n5_word_204", Kana: "としょかん", Kanji: "図書館", MeaningKo: "도서관", PartOfSpeech: "noun"},
	{ID: "n5_word_205", Kana: "びじゅつかん", Kanji: "美術館", MeaningKo: "미술관", PartOfSpeech: "noun"},
	{ID: "n5_word_206", Kana: "えいがかん", Kanji: "映画館", MeaningKo: "영화관", PartOfSpeech: "noun"},
	{ID: "n5_word_207", Kana: "けんきゅうしつ", Kanji: "研究室", MeaningKo: "연구실", PartOfSpeech: "noun"},
	{ID: "n5_word_208", Kana: "しょくどう", Kanji: "食堂", MeaningKo: "식당", PartOfSpeech: "noun"},
	{ID: "n5_word_209", Kana: "じむしょ", Kanji: "事務所", MeaningKo: "사무실", PartOfSpeech: "noun"},
	{ID: "n5_word_210", Kana: "スーパー", Kanji: "スーパー", MeaningKo: "슈퍼마켓", PartOfSpeech: "noun"},
	{ID: "n5_word_211", Kana: "コンビニ", Kanji: "コンビニ", MeaningKo: "편의점", PartOfSpeech: "noun"},
	{ID: "n5_word_212", Kana: "りょかん", Kanji: "旅館", MeaningKo: "여관", PartOfSpeech: "noun"},
	{ID: "n5_word_213", Kana: "くうこう", Kanji: "空港", MeaningKo: "공항", PartOfSpeech: "noun"},
	{ID: "n5_word_214", Kana: "こうばん", Kanji: "交番", MeaningKo: "파출소", PartOfSpeech: "noun"},
	{ID: "n5_word_215", Kana: "ほんや", Kanji: "本屋", MeaningKo: "서점", PartOfSpeech: "noun"},
	{ID: "n5_word_216", Kana: "デパート", Kanji: "デパート", MeaningKo: "백화점", PartOfSpeech: "noun"},
	{ID: "n5_word_217", Kana: "ビル", Kanji: "ビル", MeaningKo: "빌딩", PartOfSpeech: "noun"},
	{ID: "n5_word_218", Kana: "ふね", Kanji: "船", MeaningKo: "배", PartOfSpeech: "noun"},
	{ID: "n5_word_219", Kana: "ひこうき", Kanji: "飛行機", MeaningKo: "비행기", PartOfSpeech: "noun"},
	{ID: "n5_word_220", Kana: "ちかてつ", Kanji: "地下鉄", MeaningKo: "지하철", PartOfSpeech: "noun"},
	{ID: "n5_word_221", Kana: "バス", Kanji: "バス", MeaningKo: "버스", PartOfSpeech: "noun"},
	{ID: "n5_word_222", Kana: "オートバイ", Kanji: "オートバイ", MeaningKo: "오토바이", PartOfSpeech: "noun"},
	{ID: "n5_word_223", Kana: "あるく", Kanji: "歩く", MeaningKo: "걷다", PartOfSpeech: "verb"},
	{ID: "n5_word_224", Kana: "のる", Kanji: "乗る", MeaningKo: "타다", PartOfSpeech: "verb"},
	{ID: "n5_word_225", Kana: "おりる", Kanji: "降りる", MeaningKo: "내리다", PartOfSpeech: "verb"},
	{ID: "n5_word_226", Kana: "とおる", Kanji: "通る", MeaningKo: "지나다", PartOfSpeech: "verb"},
	{ID: "n5_word_227", Kana: "まがる", Kanji: "曲がる", MeaningKo: "돌다/구부러지다", PartOfSpeech: "verb"},
	{ID: "n5_word_228", Kana: "はしる", Kanji: "走る", MeaningKo: "달리다", PartOfSpeech: "verb"},
	{ID: "n5_word_229", Kana: "でんわ", Kanji: "電話", MeaningKo: "전화", PartOfSpeech: "noun"},
	{ID: "n5_word_230", Kana: "けいたい", Kanji: "携帯", MeaningKo: "휴대폰", PartOfSpeech: "noun"},
	{ID: "n5_word_231", Kana: "けしゴム", Kanji: "消しゴム", MeaningKo: "지우개", PartOfSpeech: "noun"},
	{ID: "n5_word_232", Kana: "えんぴつ", Kanji: "鉛筆", MeaningKo: "연필", PartOfSpeech: "noun"},
	{ID: "n5_word_233", Kana: "ボールペン", Kanji: "ボールペン", MeaningKo: "볼펜", PartOfSpeech: "noun"},
	{ID: "n5_word_234", Kana: "ノート", Kanji: "ノート", MeaningKo: "노트", PartOfSpeech: "noun"},
	{ID: "n5_word_235", Kana: "かみ", Kanji: "紙", MeaningKo: "종이", PartOfSpeech: "noun"},
	{ID: "n5_word_236", Kana: "とけい", Kanji: "時計", MeaningKo: "시계", PartOfSpeech: "noun"},
	{ID: "n5_word_237", Kana: "かばん", Kanji: "鞄", MeaningKo: "가방", PartOfSpeech: "noun"},
	{ID: "n5_word_238", Kana: "さいふ", Kanji: "財布", MeaningKo: "지갑", PartOfSpeech: "noun"},
	{ID: "n5_word_239", Kana: "かさ", Kanji: "傘", MeaningKo: "우산", PartOfSpeech: "noun"},
	{ID: "n5_word_240", Kana: "くつ", Kanji: "靴", MeaningKo: "신발", PartOfSpeech: "noun"},
	{ID: "n5_word_241", Kana: "ふく", Kanji: "服", MeaningKo: "옷", PartOfSpeech: "noun"},
	{ID: "n5_word_242", Kana: "めがね", Kanji: "眼鏡", MeaningKo: "안경", PartOfSpeech: "noun"},
	{ID: "n5_word_243", Kana: "シャツ", Kanji: "シャツ", MeaningKo: "셔츠", PartOfSpeech: "noun"},
	{ID: "n5_word_244", Kana: "スカート", Kanji: "スカート", MeaningKo: "스커트", PartOfSpeech: "noun"},
	{ID: "n5_word_245", Kana: "ズボン", Kanji: "ズボン", MeaningKo: "바지", PartOfSpeech: "noun"},
	{ID: "n5_word_246", Kana: "セーター", Kanji: "セーター", MeaningKo: "스웨터", PartOfSpeech: "noun"},
	{ID: "n5_word_247", Kana: "てぶくろ", Kanji: "手袋", MeaningKo: "장갑", PartOfSpeech: "noun"},
	{ID: "n5_word_248", Kana: "マフラー", Kanji: "マフラー", MeaningKo: "목도리", PartOfSpeech: "noun"},
	{ID: "n5_word_249", Kana: "ハンカチ", Kanji: "ハンカチ", MeaningKo: "손수건", PartOfSpeech: "noun"},
	{ID: "n5_word_250", Kana: "タオル", Kanji: "タオル", MeaningKo: "수건", PartOfSpeech: "noun"},
	{ID: "n5_word_251", Kana: "ラーメン", Kanji: "ラーメン", MeaningKo: "라면", PartOfSpeech: "noun"},
	{ID: "n5_word_252", Kana: "うどん", Kanji: "うどん", MeaningKo: "우동", PartOfSpeech: "noun"},
	{ID: "n5_word_253", Kana: "そば", Kanji: "そば", MeaningKo: "메밀국수", PartOfSpeech: "noun"},
	{ID: "n5_word_254", Kana: "すし", Kanji: "寿司", MeaningKo: "초밥", PartOfSpeech: "noun"},
	{ID: "n5_word_255", Kana: "てんぷら", Kanji: "天ぷら", MeaningKo: "튀김", PartOfSpeech: "noun"},
	{ID: "n5_word_256", Kana: "みそしる", Kanji: "味噌汁", MeaningKo: "된장국", PartOfSpeech: "noun"},
	{ID: "n5_word_257", Kana: "カレー", Kanji: "カレー", MeaningKo: "카레", PartOfSpeech: "noun"},
	{ID: "n5_word_258", Kana: "おかし", Kanji: "お菓子", MeaningKo: "과자", PartOfSpeech: "noun"},
	{ID: "n5_word_259", Kana: "ケーキ", Kanji: "ケーキ", MeaningKo: "케이크", PartOfSpeech: "noun"},
	{ID: "n5_word_260", Kana: "ジュース", Kanji: "ジュース", MeaningKo: "주스", PartOfSpeech: "noun"},
	{ID: "n5_word_261", Kana: "ビール", Kanji: "ビール", MeaningKo: "맥주", PartOfSpeech: "noun"},
	{ID: "n5_word_262", Kana: "ワイン", Kanji: "ワイン", MeaningKo: "와인", PartOfSpeech: "noun"},
	{ID: "n5_word_263", Kana: "ぎゅうにゅう", Kanji: "牛乳", MeaningKo: "우유", PartOfSpeech: "noun"},
	{ID: "n5_word_264", Kana: "サラダ", Kanji: "サラダ", MeaningKo: "샐러드", PartOfSpeech: "noun"},
	{ID: "n5_word_265", Kana: "スープ", Kanji: "スープ", MeaningKo: "수프", PartOfSpeech: "noun"},
	{ID: "n5_word_266", Kana: "あまい", Kanji: "甘い", MeaningKo: "달다", PartOfSpeech: "adjective"},
	{ID: "n5_word_267", Kana: "からい", Kanji: "辛い", MeaningKo: "맵다", PartOfSpeech: "adjective"},
	{ID: "n5_word_268", Kana: "かお", Kanji: "顔", MeaningKo: "얼굴", PartOfSpeech: "noun"},
	{ID: "n5_word_269", Kana: "め", Kanji: "目", MeaningKo: "눈", PartOfSpeech: "noun"},
	{ID: "n5_word_270", Kana: "はな", Kanji: "鼻", MeaningKo: "코", PartOfSpeech: "noun"},
	{ID: "n5_word_271", Kana: "くち", Kanji: "口", MeaningKo: "입", PartOfSpeech: "noun"},
	{ID: "n5_word_272", Kana: "みみ", Kanji: "耳", MeaningKo: "귀", PartOfSpeech: "noun"},
	{ID: "n5_word_273", Kana: "あたま", Kanji: "頭", MeaningKo: "머리", PartOfSpeech: "noun"},
	{ID: "n5_word_274", Kana: "て", Kanji: "手", MeaningKo: "손", PartOfSpeech: "noun"},
	{ID: "n5_word_275", Kana: "あし", Kanji: "足", MeaningKo: "다리/발", PartOfSpeech: "noun"},
	{ID: "n5_word_276", Kana: "おなか", Kanji: "お腹", MeaningKo: "배", PartOfSpeech: "noun"},
	{ID: "n5_word_277", Kana: "せなか", Kanji: "背中", MeaningKo: "등", PartOfSpeech: "noun"},
	{ID: "n5_word_278", Kana: "くび", Kanji: "首", MeaningKo: "목", PartOfSpeech: "noun"},
	{ID: "n5_word_279", Kana: "びょうき", Kanji: "病気", MeaningKo: "병", PartOfSpeech: "noun"},
	{ID: "n5_word_280", Kana: "いたい", Kanji: "痛い", MeaningKo: "아프다", PartOfSpeech: "adjective"},
	{ID: "n5_word_281", Kana: "げんき", Kanji: "元気", MeaningKo: "건강함", PartOfSpeech: "noun"},
	{ID: "n5_word_282", Kana: "くすり", Kanji: "薬", MeaningKo: "약", PartOfSpeech: "noun"},
	{ID: "n5_word_283", Kana: "ねつ", Kanji: "熱", MeaningKo: "열", PartOfSpeech: "noun"},
	{ID: "n5_word_284", Kana: "かぜ", Kanji: "風邪", MeaningKo: "감기", PartOfSpeech: "noun"},
	{ID: "n5_word_285", Kana: "てんき", Kanji: "天気", MeaningKo: "날씨", PartOfSpeech: "noun"},
	{ID: "n5_word_286", Kana: "はれ", Kanji: "晴れ", MeaningKo: "맑음", PartOfSpeech: "noun"},
	{ID: "n5_word_287", Kana: "くもり", Kanji: "曇り", MeaningKo: "흐림", PartOfSpeech: "noun"},
	{ID: "n5_word_288", Kana: "たいふう", Kanji: "台風", MeaningKo: "태풍", PartOfSpeech: "noun"},
	{ID: "n5_word_289", Kana: "きおん", Kanji: "気温", MeaningKo: "기온", PartOfSpeech: "noun"},
	{ID: "n5_word_290", Kana: "あたたかい", Kanji: "暖かい", MeaningKo: "따뜻하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_291", Kana: "すずしい", Kanji: "涼しい", MeaningKo: "시원하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_292", Kana: "しぜん", Kanji: "自然", MeaningKo: "자연", PartOfSpeech: "noun"},
	{ID: "n5_word_293", Kana: "たいよう", Kanji: "太陽", MeaningKo: "태양", PartOfSpeech: "noun"},
	{ID: "n5_word_294", Kana: "ほし", Kanji: "星", MeaningKo: "별", PartOfSpeech: "noun"},
	{ID: "n5_word_295", Kana: "そら", Kanji: "空", MeaningKo: "하늘", PartOfSpeech: "noun"},
	{ID: "n5_word_296", Kana: "うみ", Kanji: "海", MeaningKo: "바다", PartOfSpeech: "noun"},
	{ID: "n5_word_297", Kana: "きせつ", Kanji: "季節", MeaningKo: "계절", PartOfSpeech: "noun"},
	{ID: "n5_word_298", Kana: "はる", Kanji: "春", MeaningKo: "봄", PartOfSpeech: "noun"},
	{ID: "n5_word_299", Kana: "なつ", Kanji: "夏", MeaningKo: "여름", PartOfSpeech: "noun"},
	{ID: "n5_word_300", Kana: "ふゆ", Kanji: "冬", MeaningKo: "겨울", PartOfSpeech: "noun"},
	{ID: "n5_word_301", Kana: "がんばる", Kanji: "頑張る", MeaningKo: "열심히 하다", PartOfSpeech: "verb"},
	{ID: "n5_word_302", Kana: "たつ", Kanji: "立つ", MeaningKo: "서다", PartOfSpeech: "verb"},
	{ID: "n5_word_303", Kana: "おしえる", Kanji: "教える", MeaningKo: "가르치다", PartOfSpeech: "verb"},
	{ID: "n5_word_304", Kana: "ならう", Kanji: "習う", MeaningKo: "배우다", PartOfSpeech: "verb"},
	{ID: "n5_word_305", Kana: "べんきょうする", Kanji: "勉強する", MeaningKo: "공부하다", PartOfSpeech: "verb"},
	{ID: "n5_word_306", Kana: "しつもん", Kanji: "質問", MeaningKo: "질문", PartOfSpeech: "noun"},
	{ID: "n5_word_307", Kana: "こたえ", Kanji: "答え", MeaningKo: "답/대답", PartOfSpeech: "noun"},
	{ID: "n5_word_308", Kana: "テスト", Kanji: "テスト", MeaningKo: "시험", PartOfSpeech: "noun"},
	{ID: "n5_word_309", Kana: "しゅくだい", Kanji: "宿題", MeaningKo: "숙제", PartOfSpeech: "noun"},
	{ID: "n5_word_310", Kana: "えんぴつけずり", Kanji: "鉛筆削り", MeaningKo: "연필깎이", PartOfSpeech: "noun"},
	{ID: "n5_word_311", Kana: "ふでばこ", Kanji: "筆箱", MeaningKo: "필통", PartOfSpeech: "noun"},
	{ID: "n5_word_312", Kana: "ペン", Kanji: "ペン", MeaningKo: "펜", PartOfSpeech: "noun"},
	{ID: "n5_word_313", Kana: "きょうかしょ", Kanji: "教科書", MeaningKo: "교과서", PartOfSpeech: "noun"},
	{ID: "n5_word_314", Kana: "かぎ", Kanji: "鍵", MeaningKo: "열쇠", PartOfSpeech: "noun"},
	{ID: "n5_word_315", Kana: "けいさつ", Kanji: "警察", MeaningKo: "경찰", PartOfSpeech: "noun"},
	{ID: "n5_word_316", Kana: "かぞく", Kanji: "家族", MeaningKo: "가족", PartOfSpeech: "noun"},
	{ID: "n5_word_317", Kana: "あさごはん", Kanji: "朝ご飯", MeaningKo: "아침밥", PartOfSpeech: "noun"},
	{ID: "n5_word_318", Kana: "ひるごはん", Kanji: "昼ご飯", MeaningKo: "점심밥", PartOfSpeech: "noun"},
	{ID: "n5_word_319", Kana: "ばんごはん", Kanji: "晩ご飯", MeaningKo: "저녁밥", PartOfSpeech: "noun"},
	{ID: "n5_word_320", Kana: "おふろ", Kanji: "お風呂", MeaningKo: "목욕", PartOfSpeech: "noun"},
	{ID: "n5_word_321", Kana: "ねる", Kanji: "寝る", MeaningKo: "자다", PartOfSpeech: "verb"},
	{ID: "n5_word_322", Kana: "おきる", Kanji: "起きる", MeaningKo: "일어나다", PartOfSpeech: "verb"},
	{ID: "n5_word_323", Kana: "はをみがく", Kanji: "歯を磨く", MeaningKo: "이를 닦다", PartOfSpeech: "verb"},
	{ID: "n5_word_324", Kana: "かおをあらう", Kanji: "顔を洗う", MeaningKo: "세수하다", PartOfSpeech: "verb"},
	{ID: "n5_word_325", Kana: "シャワーをあびる", Kanji: "シャワーを浴びる", MeaningKo: "샤워하다", PartOfSpeech: "verb"},
	{ID: "n5_word_326", Kana: "ふくをきる", Kanji: "服を着る", MeaningKo: "옷을 입다", PartOfSpeech: "verb"},
	{ID: "n5_word_327", Kana: "でかける", Kanji: "出かける", MeaningKo: "외출하다", PartOfSpeech: "verb"},
	{ID: "n5_word_328", Kana: "かえる", Kanji: "帰る", MeaningKo: "돌아가다/돌아오다", PartOfSpeech: "verb"},
	{ID: "n5_word_329", Kana: "うんどうする", Kanji: "運動する", MeaningKo: "운동하다", PartOfSpeech: "verb"},
	{ID: "n5_word_330", Kana: "そうじする", Kanji: "掃除する", MeaningKo: "청소하다", PartOfSpeech: "verb"},
	{ID: "n5_word_331", Kana: "せんたくする", Kanji: "洗濯する", MeaningKo: "세탁하다", PartOfSpeech: "verb"},
	{ID: "n5_word_332", Kana: "りょうりする", Kanji: "料理する", MeaningKo: "요리하다", PartOfSpeech: "verb"},
	{ID: "n5_word_333", Kana: "はたらく", Kanji: "働く", MeaningKo: "일하다", PartOfSpeech: "verb"},
	{ID: "n5_word_334", Kana: "やすむ", Kanji: "休む", MeaningKo: "쉬다", PartOfSpeech: "verb"},
	{ID: "n5_word_335", Kana: "あそぶ", Kanji: "遊ぶ", MeaningKo: "놀다", PartOfSpeech: "verb"},
	{ID: "n5_word_336", Kana: "およぐ", Kanji: "泳ぐ", MeaningKo: "수영하다", PartOfSpeech: "verb"},
	{ID: "n5_word_337", Kana: "もらう", Kanji: "もらう", MeaningKo: "받다", PartOfSpeech: "verb"},
	{ID: "n5_word_338", Kana: "あげる", Kanji: "あげる", MeaningKo: "주다", PartOfSpeech: "verb"},
	{ID: "n5_word_339", Kana: "かしこい", Kanji: "賢い", MeaningKo: "현명하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_340", Kana: "やさしい", Kanji: "優しい", MeaningKo: "상냥하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_341", Kana: "むずかしい", Kanji: "難しい", MeaningKo: "어렵다", PartOfSpeech: "adjective"},
	{ID: "n5_word_342", Kana: "かんたん", Kanji: "簡単", MeaningKo: "간단하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_343", Kana: "べんり", Kanji: "便利", MeaningKo: "편리하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_344", Kana: "ふべん", Kanji: "不便", MeaningKo: "불편하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_345", Kana: "たいへん", Kanji: "大変", MeaningKo: "힘들다/큰일이다", PartOfSpeech: "adjective"},
	{ID: "n5_word_346", Kana: "ひま", Kanji: "暇", MeaningKo: "한가하다", PartOfSpeech: "adjective"},
	{ID: "n5_word_347", Kana: "いそがしい", Kanji: "忙しい", MeaningKo: "바쁘다", PartOfSpeech: "adjective"},
	{ID: "n5_word_348", Kana: "さびしい", Kanji: "寂しい", MeaningKo: "외롭다", PartOfSpeech: "adjective"},
	{ID: "n5_word_349", Kana: "たのしい", Kanji: "楽しい", MeaningKo: "즐겁다", PartOfSpeech: "adjective"},
	{ID: "n5_word_350", Kana: "おもしろい", Kanji: "面白い", MeaningKo: "재미있다", PartOfSpeech: "adjective"},
	{ID: "n5_word_351", Kana: "くらい", Kanji: "暗い", MeaningKo: "어둡다", PartOfSpeech: "adjective"},
	{ID: "n5_word_352", Kana: "あかるい", Kanji: "明るい", MeaningKo: "밝다", PartOfSpeech: "adjective"},
	{ID: "n5_word_353", Kana: "せまい", Kanji: "狭い", MeaningKo: "좁다", PartOfSpeech: "adjective"},
	{ID: "n5_word_354", Kana: "ひろい", Kanji: "広い", MeaningKo: "넓다", PartOfSpeech: "adjective"},
	{ID: "n5_word_355", Kana: "とおい", Kanji: "遠い", MeaningKo: "멀다", PartOfSpeech: "adjective"},
	{ID: "n5_word_356", Kana: "ちかい", Kanji: "近い", MeaningKo: "가깝다", PartOfSpeech: "adjective"},
	{ID: "n5_word_357", Kana: "はやい", Kanji: "速い", MeaningKo: "빠르다", PartOfSpeech: "adjective"},
	{ID: "n5_word_358", Kana: "おそい", Kanji: "遅い", MeaningKo: "느리다", PartOfSpeech: "adjective"},
	{ID: "n5_word_359", Kana: "おもい", Kanji: "重い", MeaningKo: "무겁다", PartOfSpeech: "adjective"},
	{ID: "n5_word_360", Kana: "かるい", Kanji: "軽い", MeaningKo: "가볍다", PartOfSpeech: "adjective"},
	{ID: "n5_word_361", Kana: "よく", Kanji: "よく", MeaningKo: "자주/잘", PartOfSpeech: "adverb"},
	{ID: "n5_word_362", Kana: "たぶん", Kanji: "多分", MeaningKo: "아마", PartOfSpeech: "adverb"},
	{ID: "n5_word_363", Kana: "ときどき", Kanji: "時々", MeaningKo: "가끔", PartOfSpeech: "adverb"},
	{ID: "n5_word_364", Kana: "いつも", Kanji: "いつも", MeaningKo: "항상", PartOfSpeech: "adverb"},
	{ID: "n5_word_365", Kana: "ぜんぜん", Kanji: "全然", MeaningKo: "전혀", PartOfSpeech: "adverb"},
	{ID: "n5_word_366", Kana: "あまり", Kanji: "あまり", MeaningKo: "별로/그다지", PartOfSpeech: "adverb"},
	{ID: "n5_word_367", Kana: "すこし", Kanji: "少し", MeaningKo: "조금", PartOfSpeech: "adverb"},
	{ID: "n5_word_368", Kana: "たくさん", Kanji: "沢山", MeaningKo: "많이", PartOfSpeech: "adverb"},
	{ID: "n5_word_369", Kana: "もう", Kanji: "もう", MeaningKo: "벌써/더", PartOfSpeech: "adverb"},
	{ID: "n5_word_370", Kana: "まだ", Kanji: "まだ", MeaningKo: "아직", PartOfSpeech: "adverb"},
	{ID: "n5_word_371", Kana: "どれ", Kanji: "どれ", MeaningKo: "어느 것", PartOfSpeech: "pronoun"},
	{ID: "n5_word_372", Kana: "どんな", Kanji: "どんな", MeaningKo: "어떤", PartOfSpeech: "adjective"},
	{ID: "n5_word_373", Kana: "いくら", Kanji: "いくら", MeaningKo: "얼마", PartOfSpeech: "adverb"},
	{ID: "n5_word_374", Kana: "いくつ", Kanji: "いくつ", MeaningKo: "몇 개/몇 살", PartOfSpeech: "adverb"},
	{ID: "n5_word_375", Kana: "だれか", Kanji: "誰か", MeaningKo: "누군가", PartOfSpeech: "pronoun"},
	{ID: "n5_word_376", Kana: "なにか", Kanji: "何か", MeaningKo: "무언가", PartOfSpeech: "pronoun"},
	{ID: "n5_word_377", Kana: "どこか", Kanji: "どこか", MeaningKo: "어딘가", PartOfSpeech: "adverb"},
	{ID: "n5_word_378", Kana: "だれも", Kanji: "誰も", MeaningKo: "아무도 (부정)", PartOfSpeech: "pronoun"},
	{ID: "n5_word_379", Kana: "なにも", Kanji: "何も", MeaningKo: "아무것도 (부정)", PartOfSpeech: "pronoun"},
	{ID: "n5_word_380", Kana: "しかし", Kanji: "しかし", MeaningKo: "그러나", PartOfSpeech: "conjunction"},
	{ID: "n5_word_381", Kana: "それで", Kanji: "それで", MeaningKo: "그래서", PartOfSpeech: "conjunction"},
	{ID: "n5_word_382", Kana: "それから", Kanji: "それから", MeaningKo: "그리고 나서", PartOfSpeech: "conjunction"},
	{ID: "n5_word_383", Kana: "それに", Kanji: "それに", MeaningKo: "게다가", PartOfSpeech: "conjunction"},
	{ID: "n5_word_384", Kana: "または", Kanji: "または", MeaningKo: "또는", PartOfSpeech: "conjunction"},
	{ID: "n5_word_385", Kana: "とくに", Kanji: "特に", MeaningKo: "특히", PartOfSpeech: "adverb"},
	{ID: "n5_word_386", Kana: "もちろん", Kanji: "もちろん", MeaningKo: "물론", PartOfSpeech: "adverb"},
	{ID: "n5_word_387", Kana: "ずっと", Kanji: "ずっと", MeaningKo: "훨씬/쭉", PartOfSpeech: "adverb"},
	{ID: "n5_word_388", Kana: "ちょうど", Kanji: "丁度", MeaningKo: "마침/딱", PartOfSpeech: "adverb"},
	{ID: "n5_word_389", Kana: "かならず", Kanji: "必ず", MeaningKo: "반드시", PartOfSpeech: "adverb"},
	{ID: "n5_word_390", Kana: "いっぴき", Kanji: "一匹", MeaningKo: "한 마리 (작은 동물)", PartOfSpeech: "counter"},
	{ID: "n5_word_391", Kana: "にひき", Kanji: "二匹", MeaningKo: "두 마리 (작은 동물)", PartOfSpeech: "counter"},
	{ID: "n5_word_392", Kana: "さんびき", Kanji: "三匹", MeaningKo: "세 마리 (작은 동물)", PartOfSpeech: "counter"},
	{ID: "n5_word_393", Kana: "いっぽん", Kanji: "一本", MeaningKo: "한 개 (길고 가는 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_394", Kana: "にほん", Kanji: "二本", MeaningKo: "두 개 (길고 가는 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_395", Kana: "さんぼん", Kanji: "三本", MeaningKo: "세 개 (길고 가는 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_396", Kana: "いちまい", Kanji: "一枚", MeaningKo: "한 장 (얇고 평평한 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_397", Kana: "にまい", Kanji: "二枚", MeaningKo: "두 장 (얇고 평평한 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_398", Kana: "さんまい", Kanji: "三枚", MeaningKo: "세 장 (얇고 평평한 것)", PartOfSpeech: "counter"},
	{ID: "n5_word_399", Kana: "ひとつ", Kanji: "一つ", MeaningKo: "한 개", PartOfSpeech: "numeral"},
	{ID: "n5_word_400", Kana: "ふたつ", Kanji: "二つ", MeaningKo: "두 개", PartOfSpeech: "numeral"},
	{ID: "n5_word_401", Kana: "ドア", Kanji: "ドア", MeaningKo: "문", PartOfSpeech: "noun"},
	{ID: "n5_word_402", Kana: "まど", Kanji: "窓", MeaningKo: "창문", PartOfSpeech: "noun"},
	{ID: "n5_word_403", Kana: "ベッド", Kanji: "ベッド", MeaningKo: "침대", PartOfSpeech: "noun"},
	{ID: "n5_word_404", Kana: "ソファ", Kanji: "ソファ", MeaningKo: "소파", PartOfSpeech: "noun"},
	{ID: "n5_word_405", Kana: "テーブル", Kanji: "テーブル", MeaningKo: "테이블", PartOfSpeech: "noun"},
	{ID: "n5_word_406", Kana: "でんき", Kanji: "電気", MeaningKo: "전기/전등", PartOfSpeech: "noun"},
	{ID: "n5_word_407", Kana: "エアコン", Kanji: "エアコン", MeaningKo: "에어컨", PartOfSpeech: "noun"},
	{ID: "n5_word_408", Kana: "れいぞうこ", Kanji: "冷蔵庫", MeaningKo: "냉장고", PartOfSpeech: "noun"},
	{ID: "n5_word_409", Kana: "せんたくき", Kanji: "洗濯機", MeaningKo: "세탁기", PartOfSpeech: "noun"},
	{ID: "n5_word_410", Kana: "だいどころ", Kanji: "台所", MeaningKo: "부엌", PartOfSpeech: "noun"},
	{ID: "n5_word_411", Kana: "おふろば", Kanji: "お風呂場", MeaningKo: "욕실", PartOfSpeech: "noun"},
	{ID: "n5_word_412", Kana: "げんかん", Kanji: "玄関", MeaningKo: "현관", PartOfSpeech: "noun"},
	{ID: "n5_word_413", Kana: "あか", Kanji: "赤", MeaningKo: "빨강", PartOfSpeech: "noun"},
	{ID: "n5_word_414", Kana: "あおい", Kanji: "青い", MeaningKo: "파랗다", PartOfSpeech: "adjective"},
	{ID: "n5_word_415", Kana: "しろい", Kanji: "白い", MeaningKo: "하얗다", PartOfSpeech: "adjective"},
	{ID: "n5_word_416", Kana: "くろい", Kanji: "黒い", MeaningKo: "검다", PartOfSpeech: "adjective"},
	{ID: "n5_word_417", Kana: "きいろい", Kanji: "黄色い", MeaningKo: "노랗다", PartOfSpeech: "adjective"},
	{ID: "n5_word_418", Kana: "みどり", Kanji: "緑", MeaningKo: "초록", PartOfSpeech: "noun"},
	{ID: "n5_word_419", Kana: "むらさき", Kanji: "紫", MeaningKo: "보라", PartOfSpeech: "noun"},
	{ID: "n5_word_420", Kana: "ちゃいろ", Kanji: "茶色", MeaningKo: "갈색", PartOfSpeech: "noun"},
	{ID: "n5_word_421", Kana: "ピンク", Kanji: "ピンク", MeaningKo: "분홍", PartOfSpeech: "noun"},
	{ID: "n5_word_422", Kana: "おんがく", Kanji: "音楽", MeaningKo: "음악", PartOfSpeech: "noun"},
	{ID: "n5_word_423", Kana: "どくしょ", Kanji: "読書", MeaningKo: "독서", PartOfSpeech: "noun"},
	{ID: "n5_word_424", Kana: "りょこう", Kanji: "旅行", MeaningKo: "여행", PartOfSpeech: "noun"},
	{ID: "n5_word_425", Kana: "スポーツ", Kanji: "スポーツ", MeaningKo: "스포츠", PartOfSpeech: "noun"},
	{ID: "n5_word_426", Kana: "ゲーム", Kanji: "ゲーム", MeaningKo: "게임", PartOfSpeech: "noun"},
	{ID: "n5_word_427", Kana: "りょうり", Kanji: "料理", MeaningKo: "요리", PartOfSpeech: "noun"},
	{ID: "n5_word_428", Kana: "え", Kanji: "絵", MeaningKo: "그림", PartOfSpeech: "noun"},
	{ID: "n5_word_429", Kana: "うた", Kanji: "歌", MeaningKo: "노래", PartOfSpeech: "noun"},
	{ID: "n5_word_430", Kana: "ダンス", Kanji: "ダンス", MeaningKo: "춤", PartOfSpeech: "noun"},
	{ID: "n5_word_431", Kana: "うま", Kanji: "馬", MeaningKo: "말", PartOfSpeech: "noun"},
	{ID: "n5_word_432", Kana: "とり", Kanji: "鳥", MeaningKo: "새", PartOfSpeech: "noun"},
	{ID: "n5_word_433", Kana: "うし", Kanji: "牛", MeaningKo: "소", PartOfSpeech: "noun"},
	{ID: "n5_word_434", Kana: "さる", Kanji: "猿", MeaningKo: "원숭이", PartOfSpeech: "noun"},
	{ID: "n5_word_435", Kana: "ぞう", Kanji: "象", MeaningKo: "코끼리", PartOfSpeech: "noun"},
	{ID: "n5_word_436", Kana: "ライオン", Kanji: "ライオン", MeaningKo: "사자", PartOfSpeech: "noun"},
	{ID: "n5_word_437", Kana: "パンダ", Kanji: "パンダ", MeaningKo: "판다", PartOfSpeech: "noun"},
	{ID: "n5_word_438", Kana: "キリン", Kanji: "キリン", MeaningKo: "기린", PartOfSpeech: "noun"},
	{ID: "n5_word_439", Kana: "おかね", Kanji: "お金", MeaningKo: "돈", PartOfSpeech: "noun"},
	{ID: "n5_word_440", Kana: "きっぷ", Kanji: "切符", MeaningKo: "표", PartOfSpeech: "noun"},
	{ID: "n5_word_441", Kana: "ちず", Kanji: "地図", MeaningKo: "지도", PartOfSpeech: "noun"},
	{ID: "n5_word_442", Kana: "はがき", Kanji: "葉書", MeaningKo: "엽서", PartOfSpeech: "noun"},
	{ID: "n5_word_443", Kana: "きって", Kanji: "切手", MeaningKo: "우표", PartOfSpeech: "noun"},
	{ID: "n5_word_444", Kana: "でんわばんごう", Kanji: "電話番号", MeaningKo: "전화번호", PartOfSpeech: "noun"},
	{ID: "n5_word_445", Kana: "じゅうしょ", Kanji: "住所", MeaningKo: "주소", PartOfSpeech: "noun"},
	{ID: "n5_word_446", Kana: "なまえ", Kanji: "名前", MeaningKo: "이름", PartOfSpeech: "noun"},
	{ID: "n5_word_447", Kana: "コップ", Kanji: "コップ", MeaningKo: "컵", PartOfSpeech: "noun"},
	{ID: "n5_word_448", Kana: "はさみ", Kanji: "はさみ", MeaningKo: "가위", PartOfSpeech: "noun"},
	{ID: "n5_word_449", Kana: "ナイフ", Kanji: "ナイフ", MeaningKo: "나이프", PartOfSpeech: "noun"},
	{ID: "n5_word_450", Kana: "フォーク", Kanji: "フォーク", MeaningKo: "포크", PartOfSpeech: "noun"},
	{ID: "n5_word_451", Kana: "はし", Kanji: "箸", MeaningKo: "젓가락", PartOfSpeech: "noun"},
	{ID: "n5_word_452", Kana: "スプーン", Kanji: "スプーン", MeaningKo: "숟가락", PartOfSpeech: "noun"},
	{ID: "n5_word_453", Kana: "おさら", Kanji: "お皿", MeaningKo: "접시", PartOfSpeech: "noun"},
	{ID: "n5_word_454", Kana: "おちゃわん", Kanji: "お茶碗", MeaningKo: "밥그릇/찻잔", PartOfSpeech: "noun"},
	{ID: "n5_word_455", Kana: "ゴミ", Kanji: "ゴミ", MeaningKo: "쓰레기", PartOfSpeech: "noun"},
	{ID: "n5_word_456", Kana: "せっけん", Kanji: "石鹸", MeaningKo: "비누", PartOfSpeech: "noun"},
	{ID: "n5_word_457", Kana: "かがみ", Kanji: "鏡", MeaningKo: "거울", PartOfSpeech: "noun"},
	{ID: "n5_word_458", Kana: "かべ", Kanji: "壁", MeaningKo: "벽", PartOfSpeech: "noun"},
	{ID: "n5_word_459", Kana: "ゆか", Kanji: "床", MeaningKo: "바닥", PartOfSpeech: "noun"},
	{ID: "n5_word_460", Kana: "てんじょう", Kanji: "天井", MeaningKo: "천장", PartOfSpeech: "noun"},
	{ID: "n5_word_461", Kana: "あらう", Kanji: "洗う", MeaningKo: "씻다", PartOfSpeech: "verb"},
	{ID: "n5_word_462", Kana: "はく", Kanji: "履く", MeaningKo: "신다/입다 (하의)", PartOfSpeech: "verb"},
	{ID: "n5_word_463", Kana: "かぶる", Kanji: "被る", MeaningKo: "쓰다 (모자)", PartOfSpeech: "verb"},
	{ID: "n5_word_464", Kana: "かける", Kanji: "掛ける", MeaningKo: "걸다", PartOfSpeech: "verb"},
	{ID: "n5_word_465", Kana: "しめる", Kanji: "閉める", MeaningKo: "닫다", PartOfSpeech: "verb"},
	{ID: "n5_word_466", Kana: "つける", Kanji: "点ける", MeaningKo: "켜다 (불, 전기)", PartOfSpeech: "verb"},
	{ID: "n5_word_467", Kana: "けす", Kanji: "消す", MeaningKo: "끄다 (불, 전기)", PartOfSpeech: "verb"},
	{ID: "n5_word_468", Kana: "わすれる", Kanji: "忘れる", MeaningKo: "잊다", PartOfSpeech: "verb"},
	{ID: "n5_word_469", Kana: "しぬ", Kanji: "死ぬ", MeaningKo: "죽다", PartOfSpeech: "verb"},
	{ID: "n5_word_470", Kana: "いきる", Kanji: "生きる", MeaningKo: "살다", PartOfSpeech: "verb"},
	{ID: "n5_word_471", Kana: "むすこ", Kanji: "息子", MeaningKo: "아들", PartOfSpeech: "noun"},
	{ID: "n5_word_472", Kana: "むすめ", Kanji: "娘", MeaningKo: "딸", PartOfSpeech: "noun"},
	{ID: "n5_word_473", Kana: "しゅじん", Kanji: "主人", MeaningKo: "남편", PartOfSpeech: "noun"},
	{ID: "n5_word_474", Kana: "おくさん", Kanji: "奥さん", MeaningKo: "아내", PartOfSpeech: "noun"},
	{ID: "n5_word_475", Kana: "りょうしん", Kanji: "両親", MeaningKo: "부모님", PartOfSpeech: "noun"},
	{ID: "n5_word_476", Kana: "こいびと", Kanji: "恋人", MeaningKo: "연인", PartOfSpeech: "noun"},
	{ID: "n5_word_477", Kana: "せいねん", Kanji: "青年", MeaningKo: "청년", PartOfSpeech: "noun"},
	{ID: "n5_word_478", Kana: "おとな", Kanji: "大人", MeaningKo: "어른", PartOfSpeech: "noun"},
	{ID: "n5_word_479", Kana: "あかちゃん", Kanji: "赤ちゃん", MeaningKo: "아기", PartOfSpeech: "noun"},
	{ID: "n5_word_480", Kana: "ふたり", Kanji: "二人", MeaningKo: "두 사람", PartOfSpeech: "numeral"},
	{ID: "n5_word_481", Kana: "せんじつ", Kanji: "先日", MeaningKo: "요전날", PartOfSpeech: "noun"},
	{ID: "n5_word_482", Kana: "さくばん", Kanji: "昨晩", MeaningKo: "지난밤", PartOfSpeech: "noun"},
	{ID: "n5_word_483", Kana: "こんばん", Kanji: "今晩", MeaningKo: "오늘 밤", PartOfSpeech: "noun"},
	{ID: "n5_word_484", Kana: "まいしゅう", Kanji: "毎週", MeaningKo: "매주", PartOfSpeech: "noun"},
	{ID: "n5_word_485", Kana: "まいつき", Kanji: "毎月", MeaningKo: "매월", PartOfSpeech: "noun"},
	{ID: "n5_word_486", Kana: "まいとし", Kanji: "毎年", MeaningKo: "매년", PartOfSpeech: "noun"},
	{ID: "n5_word_487", Kana: "しょうご", Kanji: "正午", MeaningKo: "정오", PartOfSpeech: "noun"},
	{ID: "n5_word_488", Kana: "ゆうがた", Kanji: "夕方", MeaningKo: "저녁", PartOfSpeech: "noun"},
	{ID: "n5_word_489", Kana: "まよなか", Kanji: "真夜中", MeaningKo: "한밤중", PartOfSpeech: "noun"},
	{ID: "n5_word_490", Kana: "いつか", Kanji: "いつか", MeaningKo: "언젠가", PartOfSpeech: "adverb"},
	{ID: "n5_word_491", Kana: "さわる", Kanji: "触る", MeaningKo: "만지다", PartOfSpeech: "verb"},
	{ID: "n5_word_492", Kana: "つかう", Kanji: "使う", MeaningKo: "사용하다", PartOfSpeech: "verb"},
	{ID: "n5_word_493", Kana: "つくる", Kanji: "作る", MeaningKo: "만들다", PartOfSpeech: "verb"},
	{ID: "n5_word_494", Kana: "はじまる", Kanji: "始まる", MeaningKo: "시작되다", PartOfSpeech: "verb"},
	{ID: "n5_word_495", Kana: "おわる", Kanji: "終わる", MeaningKo: "끝나다", PartOfSpeech: "verb"},
	{ID: "n5_word_496", Kana: "きる", Kanji: "着る", MeaningKo: "입다 (상의)", PartOfSpeech: "verb"},
	{ID: "n5_word_497", Kana: "かける", Kanji: "掛ける", MeaningKo: "(안경을) 쓰다", PartOfSpeech: "verb"},
	{ID: "n5_word_498", Kana: "ぬぐ", Kanji: "脱ぐ", MeaningKo: "(옷을) 벗다", PartOfSpeech: "verb"},
	{ID: "n5_word_499", Kana: "つれる", Kanji: "連れる", MeaningKo: "데리고 가다", PartOfSpeech: "verb"},
	{ID: "n5_word_500", Kana: "よぶ", Kanji: "呼ぶ", MeaningKo: "부르다", PartOfSpeech: "verb"},
}
